[project]
name = 'bump-test'
description = 'python bump test'
authors = [
    { name = 'Kim Taewan', email='ssklpp@naver.com'}
]
readme = 'README.md'

[tool.bumpversion]
commit = true
tag = true
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
tag_name = "v{new_version}"
tag_message = "Version {current_version} to {new_version}"
message = "Version {current_version} to {new_version}"
current_version = "2.6.4"

[git]
refspec = "origin/main"
push = true
remote = "origin"
sign = true
sign-tag = true