[tool.bumpversion]
commit = true
tag = true
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
tag_name = "v{new_version}"
tag_message = "Bump version: {current_version} to {new_version}"
message = "Bump version: {current_version} to {new_version}"
current_version = "2.5.8"

[[tool.bumpversion.files]]
filename = "CHANGELOG.md"
search = "Unreleased"

[[tool.bumpversion.files]]
filename = "CHANGELOG.md"
search = "{current_version}...HEAD"
replace = "{current_version}...{new_version}"

[git]
refspec = "origin/master"
push = true
remote = "origin"
sign = true
sign-tag = true
